export enum ConnectorId {
    GOOGLE_WORKSPACE = 'googleWorkspace',
    ATLASSIAN = 'atlassian',
    ONEDRIVE = 'onedrive',
    SHAREPOINT_ONLINE = 'sharepointOnline',
    GMAIL = 'gmail',
    CALENDAR = 'calendar',
    DRIVE = 'drive',
    JIRA = 'jira',
    CONFLUENCE = 'confluence',
    NOTION = 'notion',
    BITBUCKET = 'bitbucket',
    OUTLOOK = 'outlook',
    OUTLOOK_CALENDAR = 'outlookCalendar',
    MICROSOFT_TEAMS = 'microsoftTeams',
    MICROSOFT_DYNAMICS_365 = 'microsoftDynamics365',
    SAP = 'sap',
    SLACK = 'slack',
    DROPBOX = 'dropbox',
    BOX = 'box',
    LINEAR = 'linear',
    UPLOAD = 'upload',
    RSS = 'rss',
    LOCAL_FS = 'localfs',
  }
  
  export enum ConnectorNames {
    GOOGLE_WORKSPACE = 'Google Workspace',
    ATLASSIAN = 'Atlassian',
    ONEDRIVE = 'OneDrive',
    SHAREPOINT_ONLINE = 'SharePoint Online',
    GMAIL = 'Gmail',
    CALENDAR = 'Calendar',
    DRIVE = 'Drive',
    JIRA = 'Jira',
    CONFLUENCE = 'Confluence',
    NOTION = 'Notion',
    BITBUCKET = 'Bitbucket',
    OUTLOOK = 'Outlook',
    OUTLOOK_CALENDAR = 'Outlook Calendar',
    MICROSOFT_TEAMS = 'Microsoft Teams',
    MICROSOFT_DYNAMICS_365 = 'Microsoft Dynamics 365',
    SAP = 'SAP',
    SLACK = 'Slack',
    DROPBOX = 'Dropbox',
    BOX = 'Box',
    LINEAR = 'Linear',
    UPLOAD = 'Uploaded Files',
    RSS = 'RSS',
    LOCAL_FS = 'Local FS',
  }
  
  export const ConnectorIdToNameMap: Record<ConnectorId, string> = {
    [ConnectorId.GOOGLE_WORKSPACE]: ConnectorNames.GOOGLE_WORKSPACE,
    [ConnectorId.ATLASSIAN]: ConnectorNames.ATLASSIAN,
    [ConnectorId.ONEDRIVE]: ConnectorNames.ONEDRIVE,
    [ConnectorId.SHAREPOINT_ONLINE]: ConnectorNames.SHAREPOINT_ONLINE,
    [ConnectorId.GMAIL]: ConnectorNames.GMAIL,
    [ConnectorId.CALENDAR]: ConnectorNames.CALENDAR,
    [ConnectorId.DRIVE]: ConnectorNames.DRIVE,
    [ConnectorId.JIRA]: ConnectorNames.JIRA,
    [ConnectorId.CONFLUENCE]: ConnectorNames.CONFLUENCE,
    [ConnectorId.NOTION]: ConnectorNames.NOTION,
    [ConnectorId.BITBUCKET]: ConnectorNames.BITBUCKET,
    [ConnectorId.OUTLOOK]: ConnectorNames.OUTLOOK,
    [ConnectorId.OUTLOOK_CALENDAR]: ConnectorNames.OUTLOOK_CALENDAR,
    [ConnectorId.MICROSOFT_TEAMS]: ConnectorNames.MICROSOFT_TEAMS,
    [ConnectorId.MICROSOFT_DYNAMICS_365]: ConnectorNames.MICROSOFT_DYNAMICS_365,
    [ConnectorId.SAP]: ConnectorNames.SAP,
    [ConnectorId.SLACK]: ConnectorNames.SLACK,
    [ConnectorId.DROPBOX]: ConnectorNames.DROPBOX,
    [ConnectorId.BOX]: ConnectorNames.BOX,
    [ConnectorId.LINEAR]: ConnectorNames.LINEAR,
    [ConnectorId.UPLOAD]: ConnectorNames.UPLOAD,
    [ConnectorId.RSS]: ConnectorNames.RSS,
    [ConnectorId.LOCAL_FS]: ConnectorNames.LOCAL_FS,
  };